"use client";

import { useEffect, useMemo, useState, type FormEvent } from "react";
import type { Session } from "@supabase/supabase-js";
import { BarChart3, Bell, CalendarDays, Camera, Check, ChevronRight, CircleDollarSign, Clock3, FolderOpen, HardDrive, Image as ImageIcon, Instagram, LayoutDashboard, LogOut, Menu, MessageCircle, Plus, Search, Settings, Sparkles, Target, Users, WandSparkles, X } from "lucide-react";
import { supabase } from "./supabase";

type Section = "dashboard"|"clients"|"records"|"calendar"|"shoots"|"content"|"storage"|"finance"|"analytics"|"settings";
type Client={id:string;name:string;instagram_handle:string|null;phone:string|null;source:string|null;content_consent:boolean;lead_status:string;created_at:string};
type Shoot={id:string;client_id:string|null;shoot_type:string|null;status:string;shoot_at:string|null;studio:string|null;location:string|null;price:number;deposit:number;deposit_paid:boolean;photo_due_at:string|null;drive_folder_url?:string|null;photo_count?:number|null;content_consent?:boolean};
type Task={id:string;title:string;due_at:string|null;status:string;kind:string};
type Payment={id:string;client_id:string|null;amount:number;type:string;paid_at:string;note:string|null};

const nav=[
 {id:"dashboard" as Section,label:"Головна",icon:LayoutDashboard},
 {id:"clients" as Section,label:"Клієнти",icon:Users},
 {id:"records" as Section,label:"Записи",icon:CalendarDays},
 {id:"calendar" as Section,label:"Календар",icon:Clock3},
 {id:"shoots" as Section,label:"Зйомки",icon:Camera},
 {id:"content" as Section,label:"Контент + Муркетолог",icon:WandSparkles},
 {id:"storage" as Section,label:"Google Drive / Фото",icon:HardDrive},
 {id:"finance" as Section,label:"Фінанси",icon:CircleDollarSign},
 {id:"analytics" as Section,label:"Аналітика",icon:BarChart3},
 {id:"settings" as Section,label:"Налаштування",icon:Settings},
];
const labels:Record<string,string>={new:"Нове звернення",qualified:"Уточнено",date_selection:"Підбір дати",waiting_deposit:"Очікує передоплату",booked:"Заброньовано",shoot_done:"Зйомка проведена",completed:"Зйомка проведена",editing:"Фото в роботі",delivered:"Завершено",lost:"Втрачено",cancelled:"Скасовано"};
const money=(v:number)=>`${Number(v||0).toLocaleString("uk-UA")} ₴`;
const dt=(v:string|null)=>v?new Intl.DateTimeFormat("uk-UA",{day:"2-digit",month:"short",year:"numeric",hour:"2-digit",minute:"2-digit"}).format(new Date(v)):"—";
function hello(){const h=new Date().getHours();if(h>=5&&h<12)return"Доброго ранку, Олю 👋";if(h<18)return"Доброго дня, Олю 👋";if(h<23)return"Доброго вечора, Олю 👋";return"Доброї ночі, Олю 👋"}

function Auth({onSignedIn}:{onSignedIn:(s:Session)=>void}){const[email,setEmail]=useState("");const[password,setPassword]=useState("");const[msg,setMsg]=useState("");const[busy,setBusy]=useState(false);async function login(e:FormEvent){e.preventDefault();setBusy(true);setMsg("");const{data,error}=await supabase.auth.signInWithPassword({email:email.trim(),password});setBusy(false);if(error){setMsg("Не вдалося увійти. Перевір email і пароль.");return}if(data.session)onSignedIn(data.session)}return <main className="auth-shell"><section className="auth-card"><div className="auth-brand"><div className="brand-mark"><Camera size={21}/></div><div><strong>Oyaka Workspace</strong><span>photo_oyaka · робоче середовище</span></div></div><p className="eyebrow">LIVE CRM</p><h1>Привіт, Олю 👋</h1><p className="muted">Увійди у свій робочий простір.</p><form className="auth-form" onSubmit={login}><label>Email<input type="email" required value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Пароль<input type="password" required value={password} onChange={e=>setPassword(e.target.value)}/></label>{msg&&<div className="auth-message">{msg}</div>}<button className="primary auth-primary" disabled={busy}>{busy?"Входжу…":"Увійти"}</button></form></section></main>}

function AddClient({session,onClose,onDone}:{session:Session;onClose:()=>void;onDone:()=>void}){const[name,setName]=useState("");const[ig,setIg]=useState("");const[phone,setPhone]=useState("");const[source,setSource]=useState("Instagram");const[consent,setConsent]=useState(false);const[busy,setBusy]=useState(false);const[err,setErr]=useState("");async function save(e:FormEvent){e.preventDefault();setBusy(true);const{error}=await supabase.from("clients").insert({user_id:session.user.id,name,instagram_handle:ig||null,phone:phone||null,source,content_consent:consent,lead_status:"new"});setBusy(false);if(error){setErr(error.message);return}onDone();onClose()}return <div className="crm-modal-backdrop" onMouseDown={onClose}><form className="crm-modal" onSubmit={save} onMouseDown={e=>e.stopPropagation()}><div className="crm-modal-head"><div><p className="eyebrow">Новий контакт</p><h2>Додати клієнта</h2></div><button type="button" className="icon-button" onClick={onClose}><X size={18}/></button></div><div className="form-grid"><label className="full">Імʼя<input required value={name} onChange={e=>setName(e.target.value)}/></label><label>Instagram<input value={ig} onChange={e=>setIg(e.target.value)} placeholder="@username"/></label><label>Телефон<input value={phone} onChange={e=>setPhone(e.target.value)} placeholder="+380..."/></label><label>Джерело<select value={source} onChange={e=>setSource(e.target.value)}><option>Instagram</option><option>Рекомендація</option><option>TikTok</option><option>Інше</option></select></label><label className="check-label"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/> Є дозвіл на контент</label></div>{err&&<div className="auth-message">{err}</div>}<div className="modal-actions"><button type="button" className="secondary" onClick={onClose}>Скасувати</button><button className="primary" disabled={busy}>{busy?"Зберігаю…":"Додати"}</button></div></form></div>}

function AddRecord({session,clients,onClose,onDone}:{session:Session;clients:Client[];onClose:()=>void;onDone:()=>void}){const[clientId,setClientId]=useState(clients[0]?.id||"");const[type,setType]=useState("Індивідуальна");const[at,setAt]=useState("");const[place,setPlace]=useState("");const[price,setPrice]=useState("");const[deposit,setDeposit]=useState("");const[paid,setPaid]=useState(false);const[busy,setBusy]=useState(false);const[err,setErr]=useState("");async function save(e:FormEvent){e.preventDefault();if(!clientId){setErr("Спочатку додай клієнта.");return}setBusy(true);const dep=Number(deposit||0);const{error}=await supabase.from("shoots").insert({user_id:session.user.id,client_id:clientId,shoot_type:type,status:paid||dep===0?"booked":"waiting_deposit",shoot_at:at?new Date(at).toISOString():null,location:place||null,price:Number(price||0),deposit:dep,deposit_paid:paid,content_consent:false});setBusy(false);if(error){setErr(error.message);return}onDone();onClose()}return <div className="crm-modal-backdrop" onMouseDown={onClose}><form className="crm-modal" onSubmit={save} onMouseDown={e=>e.stopPropagation()}><div className="crm-modal-head"><div><p className="eyebrow">Новий запис</p><h2>Забронювати зйомку</h2></div><button type="button" className="icon-button" onClick={onClose}><X size={18}/></button></div><div className="form-grid"><label className="full">Клієнт<select value={clientId} onChange={e=>setClientId(e.target.value)}>{clients.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Тип<select value={type} onChange={e=>setType(e.target.value)}><option>Індивідуальна</option><option>Love story</option><option>Сімейна</option><option>Вагітність</option><option>Дитяча</option><option>Контент</option><option>Інша</option></select></label><label>Дата й час<input type="datetime-local" required value={at} onChange={e=>setAt(e.target.value)}/></label><label className="full">Студія / локація<input value={place} onChange={e=>setPlace(e.target.value)}/></label><label>Вартість<input type="number" min="0" value={price} onChange={e=>setPrice(e.target.value)}/></label><label>Передоплата<input type="number" min="0" value={deposit} onChange={e=>setDeposit(e.target.value)}/></label><label className="check-label full"><input type="checkbox" checked={paid} onChange={e=>setPaid(e.target.checked)}/> Передоплату отримано</label></div>{err&&<div className="auth-message">{err}</div>}<div className="modal-actions"><button type="button" className="secondary" onClick={onClose}>Скасувати</button><button className="primary" disabled={busy}>{busy?"Зберігаю…":"Створити запис"}</button></div></form></div>}

function Stat({label,value,sub,Icon}:{label:string;value:string;sub:string;Icon:any}){return <div className="stat-card"><div className="stat-icon"><Icon size={19}/></div><div><p>{label}</p><strong>{value}</strong><span>{sub}</span></div></div>}

export default function RestoredCRM(){
 const[session,setSession]=useState<Session|null>(null);const[section,setSection]=useState<Section>("dashboard");const[mobile,setMobile]=useState(false);const[clients,setClients]=useState<Client[]>([]);const[shoots,setShoots]=useState<Shoot[]>([]);const[tasks,setTasks]=useState<Task[]>([]);const[payments,setPayments]=useState<Payment[]>([]);const[query,setQuery]=useState("");const[clientModal,setClientModal]=useState(false);const[recordModal,setRecordModal]=useState(false);const[loading,setLoading]=useState(false);
 useEffect(()=>{let alive=true;supabase.auth.getSession().then(({data})=>{if(alive&&data.session)setSession(data.session)}).catch(()=>{});const{data}=supabase.auth.onAuthStateChange((_e,s)=>{if(alive)setSession(s)});return()=>{alive=false;data.subscription.unsubscribe()}},[]);
 async function load(){if(!session)return;setLoading(true);const[c,s,t,p]=await Promise.all([supabase.from("clients").select("*").order("created_at",{ascending:false}),supabase.from("shoots").select("*").order("shoot_at",{ascending:false}),supabase.from("tasks").select("*").order("due_at",{ascending:true}),supabase.from("payments").select("*").order("paid_at",{ascending:false})]);setClients((c.data as Client[])||[]);setShoots((s.data as Shoot[])||[]);setTasks((t.data as Task[])||[]);setPayments((p.data as Payment[])||[]);setLoading(false)}
 useEffect(()=>{if(session)load()},[session]);
 const filtered=useMemo(()=>clients.filter(c=>`${c.name} ${c.instagram_handle||""} ${c.phone||""}`.toLowerCase().includes(query.toLowerCase())),[clients,query]);
 const clientById=useMemo(()=>Object.fromEntries(clients.map(c=>[c.id,c])),[clients]);const upcoming=shoots.filter(s=>s.shoot_at&&new Date(s.shoot_at)>=new Date()&&!['cancelled','delivered'].includes(s.status));const openTasks=tasks.filter(t=>t.status==="open");const income=payments.filter(p=>["deposit","balance"].includes(p.type)).reduce((a,p)=>a+Number(p.amount),0);const current=nav.find(n=>n.id===section)?.label;
 if(!session)return <Auth onSignedIn={setSession}/>;
 const Dashboard=()=> <><div className="page-heading"><div><p className="eyebrow">Oyaka Workspace · live CRM</p><h1>{hello()}</h1><p className="muted">Клієнти, записи, зйомки, фото й контент — в одному місці.</p></div><button className="primary" onClick={()=>setRecordModal(true)}><Plus size={17}/> Новий запис</button></div><div className="stats-grid"><Stat label="Клієнти" value={String(clients.length)} sub="у базі" Icon={Users}/><Stat label="Майбутні записи" value={String(upcoming.length)} sub="зйомок заплановано" Icon={CalendarDays}/><Stat label="Отримано оплат" value={money(income)} sub={`${payments.length} операцій`} Icon={CircleDollarSign}/><Stat label="Відкриті задачі" value={String(openTasks.length)} sub="потребують уваги" Icon={Bell}/></div><div className="dashboard-grid"><section className="panel day-panel"><div className="panel-title"><div><span className="mini-icon"><Clock3 size={16}/></span><h2>Найближчі записи</h2></div></div><div className="agenda">{upcoming.length?upcoming.slice(0,5).map(s=><div className="agenda-item" key={s.id}><div className="agenda-copy"><strong>{clientById[s.client_id||""]?.name||"Клієнт"} · {s.shoot_type||"Зйомка"}</strong><span>{dt(s.shoot_at)} · {s.location||s.studio||"локація не вказана"}</span></div><span className="soft-pill">{labels[s.status]||s.status}</span></div>):<div className="empty-state">Майбутніх записів ще немає.</div>}</div></section><section className="panel ai-card"><div className="ai-head"><div className="ai-orb"><Sparkles size={20}/></div><div><p className="eyebrow">Муркетолог 🐾</p><h2>Робочий фокус</h2></div></div><p className="ai-copy">Бачу {clients.length} клієнтів, {upcoming.length} майбутніх зйомок і {openTasks.length} задач. Далі підключимо автоматичні рекомендації до цих даних.</p></section></div></>;
 const Clients=()=> <><div className="page-heading"><div><p className="eyebrow">CRM</p><h1>Клієнти</h1><p className="muted">Контакти та історія взаємодії. Записи зберігаються окремо й не губляться.</p></div><button className="primary" onClick={()=>setClientModal(true)}><Plus size={17}/> Новий клієнт</button></div><div className="toolbar"><div className="search"><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Пошук за імʼям, Instagram або телефоном"/></div><span className="soft-pill">{clients.length} клієнтів</span></div><section className="panel table-panel"><div className="table-head"><span>Клієнт</span><span>Джерело</span><span>Контент</span><span>Статус</span><span>Записів</span></div>{loading?<div className="empty-state">Завантажую…</div>:filtered.map(c=><div className="table-row" key={c.id}><div className="client-cell"><div className="avatar">{c.name[0]}</div><div><strong>{c.name}</strong><span>{c.instagram_handle||c.phone||"—"}</span></div></div><span>{c.source||"—"}</span><span>{c.content_consent?"✓ дозволено":"—"}</span><span>{labels[c.lead_status]||c.lead_status}</span><strong>{shoots.filter(s=>s.client_id===c.id).length}</strong></div>)}</section></>;
 const Records=()=> <><div className="page-heading"><div><p className="eyebrow">Бронювання</p><h1>Записи</h1><p className="muted">Усі поточні та минулі записи клієнтів — окремою історією.</p></div><button className="primary" onClick={()=>setRecordModal(true)}><Plus size={17}/> Новий запис</button></div><section className="panel table-panel"><div className="table-head"><span>Клієнт</span><span>Тип</span><span>Дата</span><span>Сума</span><span>Статус</span></div>{shoots.length?shoots.map(s=><div className="table-row" key={s.id}><div className="client-cell"><div className="avatar">{clientById[s.client_id||""]?.name?.[0]||"?"}</div><div><strong>{clientById[s.client_id||""]?.name||"—"}</strong><span>{s.location||s.studio||"Локація не вказана"}</span></div></div><span>{s.shoot_type||"Зйомка"}</span><span>{dt(s.shoot_at)}</span><strong>{money(s.price)}</strong><span>{labels[s.status]||s.status}</span></div>):<div className="empty-state">Записів ще немає.</div>}</section></>;
 const Calendar=()=> <><div className="page-heading"><div><p className="eyebrow">Розклад</p><h1>Календар</h1><p className="muted">Зйомки, дедлайни фото й робочі задачі.</p></div><button className="primary" onClick={()=>setRecordModal(true)}><Plus size={17}/> Додати запис</button></div><section className="panel"><div className="agenda">{upcoming.length?upcoming.map(s=><div className="agenda-item" key={s.id}><div className="time">{s.shoot_at?new Date(s.shoot_at).toLocaleTimeString("uk-UA",{hour:"2-digit",minute:"2-digit"}):"—"}</div><div className="agenda-copy"><strong>{clientById[s.client_id||""]?.name||"Клієнт"} · {s.shoot_type||"Зйомка"}</strong><span>{dt(s.shoot_at)} · {s.location||"локація не вказана"}</span></div></div>):<div className="empty-state">Календар поки порожній.</div>}</div></section><div className="mini-grid"><section className="panel small-card"><h3>Нагадування</h3><p>За 24 години до зйомки CRM готує нагадування про час, локацію, образи та оплату.</p><div className="toggle-row"><span>Автоматичні задачі</span><span className="toggle on"/></div></section><section className="panel small-card"><h3>Дедлайн фото</h3><p>Після зйомки система контролює стандартний дедлайн +10 днів.</p><div className="toggle-row"><span>Контроль дедлайнів</span><span className="toggle on"/></div></section></div></>;
 const Shoots=()=> <><div className="page-heading"><div><p className="eyebrow">Проєкти</p><h1>Зйомки</h1><p className="muted">Тут запис перетворюється на робочий проєкт: файли, дедлайн, Drive і дозвіл на публікацію.</p></div><button className="primary" onClick={()=>setRecordModal(true)}><Plus size={17}/> Нова зйомка</button></div><div className="shoot-grid">{shoots.length?shoots.map((s,i)=><section className="shoot-card" key={s.id}><div className={`shoot-cover cover-${i%4+1}`}><Camera size={25}/><span>{s.shoot_type||"Зйомка"}</span></div><div className="shoot-body"><div><strong>{clientById[s.client_id||""]?.name||"Клієнт"}</strong><span>{dt(s.shoot_at)}</span></div><div className="shoot-meta"><span><FolderOpen size={15}/> {s.drive_folder_url?"Drive підключено":"Папка Drive не додана"}</span><span><ImageIcon size={15}/> {s.photo_count||0} фото</span></div><div className="permission"><span>Дозвіл на контент</span><b>{s.content_consent?"Так":"Ні"}</b></div><button className="secondary full">Відкрити зйомку</button></div></section>):<div className="empty-state">Зйомок ще немає.</div>}</div></>;
 const Content=()=> <><div className="page-heading"><div><p className="eyebrow">Мій контент-менеджер</p><h1>Контент + Муркетолог</h1><p className="muted">Ідеї, Reels, Stories, TikTok і план публікацій із готових зйомок.</p></div><button className="primary"><Sparkles size={17}/> Створити контент</button></div><section className="panel content-ai-hero"><div><span className="ai-badge"><Sparkles size={15}/> Муркетолог 🐾</span><h2>Контент без щоденного «що постити?»</h2><p>Муркетолог використовує тільки зйомки, де є дозвіл на контент, і нічого не публікує без підтвердження Олі.</p><div className="hero-actions"><button className="ai-button">Згенерувати тиждень</button><button className="secondary">Змінити ціль</button></div></div><div className="content-score"><span>Доступних зйомок</span><strong>{shoots.filter(s=>s.content_consent).length}</strong><small>із дозволом на контент</small></div></section><div className="mini-grid"><section className="panel small-card"><h3>Google Drive</h3><p>Муркетолог бачить лише дозволені папки/превʼю, а не весь диск.</p><button className="secondary" onClick={()=>setSection("storage")}>Відкрити сховище</button></section><section className="panel small-card"><h3>Instagram + TikTok</h3><p>Планування, CTA, статуси та майбутня аналітика контенту.</p><button className="secondary">Підключення — далі</button></section></div></>;
 const Storage=()=> <><div className="page-heading"><div><p className="eyebrow">Фото · сховище</p><h1>Google Drive / Фото</h1><p className="muted">Майстер-файли залишаються у Drive. CRM зберігає посилання, статус синхронізації, превʼю й дозволи.</p></div><button className="primary"><HardDrive size={17}/> Підключити Google Drive</button></div><div className="dashboard-grid"><section className="panel"><div className="panel-title"><div><span className="mini-icon"><FolderOpen size={16}/></span><h2>Структура папок</h2></div></div><div className="agenda"><div className="agenda-item"><div className="agenda-copy"><strong>Клієнти → 2026</strong><span>Основна папка робочого архіву</span></div></div><div className="agenda-item"><div className="agenda-copy"><strong>[дата]_[Клієнт]_[Тип зйомки]</strong><span>Окрема папка кожної зйомки</span></div></div><div className="agenda-item"><div className="agenda-copy"><strong>Готові фото</strong><span>Папка, яку CRM зможе синхронізувати для контенту</span></div></div></div></section><section className="panel focus-card"><p className="eyebrow">Безпека</p><h3>CRM не сканує весь Google Drive</h3><p>Доступ отримують лише явно підключені папки. Для AI — превʼю/thumbnail; full-res потрібен тільки під час експорту або публікації.</p><div className="hint"><Check size={16}/><span>Дозвіл «Використовувати для контенту» контролюється на рівні клієнта/зйомки.</span></div></section></div><section className="panel table-panel"><div className="table-head"><span>Зйомка</span><span>Клієнт</span><span>Drive</span><span>Фото</span><span>Контент</span></div>{shoots.length?shoots.map(s=><div className="table-row" key={s.id}><strong>{s.shoot_type||"Зйомка"}</strong><span>{clientById[s.client_id||""]?.name||"—"}</span><span>{s.drive_folder_url?"✓ папка":"Не підключено"}</span><span>{s.photo_count||0}</span><span>{s.content_consent?"✓ дозволено":"—"}</span></div>):<div className="empty-state">Спочатку створи записи/зйомки.</div>}</section></>;
 const Finance=()=> <><div className="page-heading"><div><p className="eyebrow">Гроші</p><h1>Фінанси</h1><p className="muted">Передоплати, баланси, витрати й дохід.</p></div><button className="primary"><Plus size={17}/> Додати платіж</button></div><div className="stats-grid"><Stat label="Отримано" value={money(income)} sub="усі надходження" Icon={CircleDollarSign}/><Stat label="Операції" value={String(payments.length)} sub="у базі" Icon={Check}/><Stat label="Майбутні записи" value={String(upcoming.length)} sub="потенційний дохід" Icon={Target}/><Stat label="Передоплата очікується" value={String(shoots.filter(s=>s.status==="waiting_deposit").length)} sub="записів" Icon={Clock3}/></div></>;
 const Analytics=()=> <><div className="page-heading"><div><p className="eyebrow">Зростання</p><h1>Аналітика</h1><p className="muted">Конверсія, джерела заявок, повторні клієнти й середній чек.</p></div></div><div className="stats-grid"><Stat label="Клієнти" value={String(clients.length)} sub="всього" Icon={Users}/><Stat label="Записи" value={String(shoots.length)} sub="за весь час" Icon={CalendarDays}/><Stat label="Instagram" value={String(clients.filter(c=>c.source==="Instagram").length)} sub="клієнтів із джерела" Icon={Instagram}/><Stat label="Середній чек" value={shoots.length?money(shoots.reduce((a,s)=>a+Number(s.price||0),0)/shoots.length):"0 ₴"} sub="за записами" Icon={CircleDollarSign}/></div><section className="panel insight-panel"><div className="ai-orb"><Sparkles size={20}/></div><div><p className="eyebrow">Муркетолог радить</p><h3>Аналітика вже бере основу з живих клієнтів і записів.</h3><p>Далі додамо точний funnel: звернення → дата → передоплата → зйомка → повторний продаж.</p></div></section></>;
 const SettingsPage=()=> <><div className="page-heading"><div><p className="eyebrow">Система</p><h1>Налаштування</h1><p className="muted">Доступи, автоматизації, інтеграції та правила роботи CRM.</p></div></div><div className="mini-grid"><section className="panel small-card"><h3>Користувачі й ролі</h3><p>Власник/Адмін та Фотограф. Розширене керування ролями додамо окремим модулем.</p><button className="secondary">Керування доступами</button></section><section className="panel small-card"><h3>Автоматичні задачі</h3><p>Підготовка за 24 години, контроль передоплати, дедлайн фото +10 днів.</p><div className="toggle-row"><span>Автоматизації</span><span className="toggle on"/></div></section><section className="panel small-card"><h3>Google Drive</h3><p>Підключення папок готових фото та контроль синхронізації.</p><button className="secondary" onClick={()=>setSection("storage")}>Налаштувати Drive</button></section><section className="panel small-card"><h3>Соцмережі</h3><p>Instagram / TikTok — підключимо після контентного модуля.</p><button className="secondary">Налаштувати</button></section></div></>;
 return <main className="app-shell"><aside className={`sidebar ${mobile?"open":""}`}><div className="brand"><div className="brand-mark"><Camera size={20}/></div><div><strong>Oyaka Workspace</strong><span>photo_oyaka · live CRM</span></div></div><button className="mobile-close" onClick={()=>setMobile(false)}><X size={20}/></button><nav>{nav.map(i=>{const Icon=i.icon;return <button key={i.id} className={section===i.id?"nav-item active":"nav-item"} onClick={()=>{setSection(i.id);setMobile(false)}}><Icon size={18}/><span>{i.label}</span>{i.id==="content"&&<em>🐾</em>}</button>})}</nav><div className="sidebar-bottom"><button className="storage-card" onClick={()=>setSection("storage")}><FolderOpen size={17}/><div><strong>Сховище фото</strong><span>Google Drive · налаштувати</span></div><ChevronRight size={16}/></button><div className="profile"><div className="profile-avatar">О</div><div><strong>Оля</strong><span>{session.user.email}</span></div><button title="Вийти" onClick={()=>supabase.auth.signOut()}><LogOut size={16}/></button></div></div></aside>{mobile&&<div className="overlay" onClick={()=>setMobile(false)}/>}<div className="workspace"><header className="topbar"><button className="menu-button" onClick={()=>setMobile(true)}><Menu size={20}/></button><span className="top-title">{current}</span><div className="top-actions"><button className="icon-button"><Search size={18}/></button><button className="icon-button notification"><Bell size={18}/><i/></button><button className="quick-add" onClick={()=>setRecordModal(true)}><Plus size={17}/> Запис</button></div></header><div className="page-content">{section==="dashboard"&&<Dashboard/>}{section==="clients"&&<Clients/>}{section==="records"&&<Records/>}{section==="calendar"&&<Calendar/>}{section==="shoots"&&<Shoots/>}{section==="content"&&<Content/>}{section==="storage"&&<Storage/>}{section==="finance"&&<Finance/>}{section==="analytics"&&<Analytics/>}{section==="settings"&&<SettingsPage/>}</div></div>{clientModal&&<AddClient session={session} onClose={()=>setClientModal(false)} onDone={load}/>} {recordModal&&<AddRecord session={session} clients={clients} onClose={()=>setRecordModal(false)} onDone={load}/>}</main>
}
