"use client";

import { useEffect, useMemo, useState, type FormEvent } from "react";
import type { Session } from "@supabase/supabase-js";
import { BarChart3, Bell, CalendarDays, Camera, CircleDollarSign, LayoutDashboard, LogOut, Menu, Plus, Search, Sparkles, Users, WandSparkles, X } from "lucide-react";
import { supabase } from "./supabase";

type Section = "dashboard" | "clients" | "calendar" | "shoots" | "content" | "finance" | "analytics";
type Client = { id:string; name:string; instagram_handle:string|null; phone:string|null; source:string|null; content_consent:boolean; lead_status:string; created_at:string };
type Shoot = { id:string; client_id:string|null; shoot_type:string|null; status:string; shoot_at:string|null; studio:string|null; location:string|null; price:number; deposit:number; deposit_paid:boolean; photo_due_at:string|null };
type Task = { id:string; title:string; due_at:string|null; status:string; kind:string };
type Payment = { id:string; client_id:string|null; amount:number; type:string; paid_at:string; note:string|null };

const nav = [
  {id:"dashboard" as Section,label:"Головна",icon:LayoutDashboard},
  {id:"clients" as Section,label:"Клієнти",icon:Users},
  {id:"calendar" as Section,label:"Календар",icon:CalendarDays},
  {id:"shoots" as Section,label:"Зйомки",icon:Camera},
  {id:"content" as Section,label:"Контент + Муркетолог",icon:WandSparkles},
  {id:"finance" as Section,label:"Фінанси",icon:CircleDollarSign},
  {id:"analytics" as Section,label:"Аналітика",icon:BarChart3},
];

const labels:Record<string,string> = {new:"Нове звернення",qualified:"Уточнено",date_selection:"Підбір дати",waiting_deposit:"Очікує передоплату",booked:"Заброньовано",shoot_done:"Зйомка проведена",completed:"Зйомка проведена",editing:"Фото в роботі",delivered:"Завершено",lost:"Втрачено",cancelled:"Скасовано"};
const money = (v:number) => `${Number(v||0).toLocaleString("uk-UA")} ₴`;
const dt = (v:string|null) => v ? new Intl.DateTimeFormat("uk-UA",{day:"numeric",month:"short",year:"numeric",hour:"2-digit",minute:"2-digit"}).format(new Date(v)) : "—";
function greeting(){ const h = new Date().getHours(); if(h>=5&&h<12)return "Доброго ранку, Олю 👋"; if(h>=12&&h<18)return "Доброго дня, Олю 👋"; if(h>=18&&h<23)return "Доброго вечора, Олю 👋"; return "Доброї ночі, Олю 👋"; }

function Auth({onSignedIn}:{onSignedIn:(s:Session)=>void}){
  const [email,setEmail]=useState(""); const [password,setPassword]=useState(""); const [msg,setMsg]=useState(""); const [busy,setBusy]=useState(false);
  async function login(e:FormEvent){
    e.preventDefault(); setBusy(true); setMsg("");
    const {data,error}=await supabase.auth.signInWithPassword({email:email.trim(),password});
    setBusy(false);
    if(error){setMsg("Не вдалося увійти. Перевір email і пароль.");return;}
    if(data.session){onSignedIn(data.session);return;}
    setMsg("Вхід підтверджено, але сесію не отримано. Онови сторінку й спробуй ще раз.");
  }
  return <main className="auth-shell"><section className="auth-card"><div className="auth-brand"><div className="brand-mark"><Camera size={21}/></div><div><strong>Oyaka Workspace</strong><span>photo_oyaka · робоче середовище</span></div></div><p className="eyebrow">LIVE CRM</p><h1>Привіт, Олю 👋</h1><p className="muted">Увійди у свій робочий простір.</p><form className="auth-form" onSubmit={login}><label>Email<input type="email" autoComplete="email" required value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Пароль<input type="password" autoComplete="current-password" required value={password} onChange={e=>setPassword(e.target.value)}/></label>{msg&&<div className="auth-message">{msg}</div>}<button className="primary auth-primary" disabled={busy}>{busy?"Входжу…":"Увійти"}</button></form></section></main>;
}

function AddClient({session,onClose,onDone}:{session:Session;onClose:()=>void;onDone:()=>void}){
  const [name,setName]=useState(""); const [ig,setIg]=useState(""); const [phone,setPhone]=useState(""); const [source,setSource]=useState("Instagram"); const [consent,setConsent]=useState(false); const [busy,setBusy]=useState(false); const [err,setErr]=useState("");
  async function save(e:FormEvent){e.preventDefault();setBusy(true);const{error}=await supabase.from("clients").insert({user_id:session.user.id,name,instagram_handle:ig||null,phone:phone||null,source,content_consent:consent,lead_status:"new"});setBusy(false);if(error){setErr(error.message);return;}onDone();onClose();}
  return <div className="crm-modal-backdrop" onMouseDown={onClose}><form className="crm-modal" onSubmit={save} onMouseDown={e=>e.stopPropagation()}><div className="crm-modal-head"><div><p className="eyebrow">Новий контакт</p><h2>Додати клієнта</h2></div><button type="button" className="icon-button" onClick={onClose}><X size={18}/></button></div><div className="form-grid"><label className="full">Імʼя<input required value={name} onChange={e=>setName(e.target.value)} placeholder="Марія Коваль"/></label><label>Instagram<input value={ig} onChange={e=>setIg(e.target.value)} placeholder="@maria"/></label><label>Телефон<input value={phone} onChange={e=>setPhone(e.target.value)} placeholder="+380..."/></label><label>Джерело<select value={source} onChange={e=>setSource(e.target.value)}><option>Instagram</option><option>Рекомендація</option><option>TikTok</option><option>Інше</option></select></label><label className="check-label"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/> Є дозвіл на контент</label></div>{err&&<div className="auth-message">{err}</div>}<div className="modal-actions"><button type="button" className="secondary" onClick={onClose}>Скасувати</button><button className="primary" disabled={busy}>{busy?"Зберігаю…":"Додати"}</button></div></form></div>;
}

function AddShoot({session,clients,initialClient,onClose,onDone}:{session:Session;clients:Client[];initialClient?:string;onClose:()=>void;onDone:()=>void}){
  const [clientId,setClientId]=useState(initialClient||clients[0]?.id||""); const [type,setType]=useState("Індивідуальна"); const [at,setAt]=useState(""); const [place,setPlace]=useState(""); const [price,setPrice]=useState(""); const [deposit,setDeposit]=useState(""); const [paid,setPaid]=useState(false); const [err,setErr]=useState(""); const [busy,setBusy]=useState(false);
  async function save(e:FormEvent){e.preventDefault();if(!clientId){setErr("Оберіть клієнта");return;}setBusy(true);const dep=Number(deposit||0);const{error}=await supabase.from("shoots").insert({user_id:session.user.id,client_id:clientId,shoot_type:type,status:paid||dep===0?"booked":"waiting_deposit",shoot_at:at?new Date(at).toISOString():null,location:place||null,price:Number(price||0),deposit:dep,deposit_paid:paid,content_consent:false});setBusy(false);if(error){setErr(error.message);return;}onDone();onClose();}
  return <div className="crm-modal-backdrop" onMouseDown={onClose}><form className="crm-modal" onSubmit={save} onMouseDown={e=>e.stopPropagation()}><div className="crm-modal-head"><div><p className="eyebrow">Новий запис</p><h2>Створити зйомку</h2></div><button type="button" className="icon-button" onClick={onClose}><X size={18}/></button></div><div className="form-grid"><label className="full">Клієнт<select value={clientId} onChange={e=>setClientId(e.target.value)}>{clients.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Тип<select value={type} onChange={e=>setType(e.target.value)}><option>Індивідуальна</option><option>Love story</option><option>Сімейна</option><option>Вагітність</option><option>Дитяча</option><option>Контент</option><option>Інша</option></select></label><label>Дата і час<input type="datetime-local" required value={at} onChange={e=>setAt(e.target.value)}/></label><label className="full">Студія / локація<input value={place} onChange={e=>setPlace(e.target.value)} placeholder="Студія або адреса"/></label><label>Вартість<input type="number" min="0" value={price} onChange={e=>setPrice(e.target.value)} placeholder="3000"/></label><label>Передоплата<input type="number" min="0" value={deposit} onChange={e=>setDeposit(e.target.value)} placeholder="1000"/></label><label className="check-label full"><input type="checkbox" checked={paid} onChange={e=>setPaid(e.target.checked)}/> Передоплату отримано</label></div>{err&&<div className="auth-message">{err}</div>}<div className="modal-actions"><button type="button" className="secondary" onClick={onClose}>Скасувати</button><button className="primary" disabled={busy}>{busy?"Зберігаю…":"Створити запис"}</button></div></form></div>;
}

function Stat({label,value,sub,Icon}:{label:string;value:string;sub:string;Icon:any}){return <div className="stat-card"><div className="stat-icon"><Icon size={19}/></div><div><p>{label}</p><strong>{value}</strong><span>{sub}</span></div></div>}

export default function CrmV2(){
  const [session,setSession]=useState<Session|null>(null); const [section,setSection]=useState<Section>("dashboard"); const [mobile,setMobile]=useState(false); const [clients,setClients]=useState<Client[]>([]); const [shoots,setShoots]=useState<Shoot[]>([]); const [tasks,setTasks]=useState<Task[]>([]); const [payments,setPayments]=useState<Payment[]>([]); const [query,setQuery]=useState(""); const [clientModal,setClientModal]=useState(false); const [shootModal,setShootModal]=useState(false); const [selectedClient,setSelectedClient]=useState<string>(""); const [murketolog,setMurketolog]=useState(false); const [loading,setLoading]=useState(false); const [hello,setHello]=useState("Доброго дня, Олю 👋");

  useEffect(()=>{setHello(greeting());let mounted=true;supabase.auth.getSession().then(({data})=>{if(mounted&&data.session)setSession(data.session)}).catch(()=>{});const{data}=supabase.auth.onAuthStateChange((_e,s)=>{if(mounted)setSession(s)});return()=>{mounted=false;data.subscription.unsubscribe();};},[]);

  async function load(){if(!session)return;setLoading(true);const[c,s,t,p]=await Promise.all([supabase.from("clients").select("*").order("created_at",{ascending:false}),supabase.from("shoots").select("*").order("shoot_at",{ascending:false}),supabase.from("tasks").select("*").order("due_at",{ascending:true}),supabase.from("payments").select("*").order("paid_at",{ascending:false})]);setClients((c.data as Client[])||[]);setShoots((s.data as Shoot[])||[]);setTasks((t.data as Task[])||[]);setPayments((p.data as Payment[])||[]);setLoading(false);}
  useEffect(()=>{if(session)load();else{setClients([]);setShoots([]);setTasks([]);setPayments([]);}},[session]);

  const filtered=useMemo(()=>clients.filter(c=>`${c.name} ${c.instagram_handle||""} ${c.phone||""}`.toLowerCase().includes(query.toLowerCase())),[clients,query]);
  const clientById=useMemo(()=>Object.fromEntries(clients.map(c=>[c.id,c])),[clients]);
  const openTasks=tasks.filter(t=>t.status==="open"); const upcoming=shoots.filter(s=>s.shoot_at&&new Date(s.shoot_at)>=new Date()); const income=payments.filter(p=>["deposit","balance"].includes(p.type)).reduce((a,p)=>a+Number(p.amount),0); const current=nav.find(n=>n.id===section)?.label;

  if(!session)return <Auth onSignedIn={setSession}/>;

  const Dashboard=()=> <><div className="page-heading"><div><p className="eyebrow">Oyaka Workspace · live CRM</p><h1>{hello}</h1><p className="muted">Клієнти, записи, задачі та фінанси в одному місці.</p></div><button className="primary" onClick={()=>setClientModal(true)}><Plus size={17}/> Додати клієнта</button></div><div className="stats-grid"><Stat label="Клієнти" value={String(clients.length)} sub="у базі" Icon={Users}/><Stat label="Майбутні зйомки" value={String(upcoming.length)} sub="у календарі" Icon={CalendarDays}/><Stat label="Отримано оплат" value={money(income)} sub={`${payments.length} операцій`} Icon={CircleDollarSign}/><Stat label="Відкриті задачі" value={String(openTasks.length)} sub="потребують уваги" Icon={Bell}/></div><div className="dashboard-grid"><section className="panel"><div className="panel-title"><h2>Найближчі зйомки</h2></div><div className="agenda">{upcoming.length?upcoming.slice(0,5).map(s=><div className="agenda-item" key={s.id}><div className="agenda-copy"><strong>{clientById[s.client_id||""]?.name||"Клієнт"} · {s.shoot_type||"Зйомка"}</strong><span>{dt(s.shoot_at)}</span></div><span className="soft-pill">{labels[s.status]||s.status}</span></div>):<div className="empty-state">Поки немає майбутніх записів.</div>}</div></section><section className="panel ai-card"><div className="ai-head"><div className="ai-orb"><Sparkles size={20}/></div><div><p className="eyebrow">Муркетолог 🐾</p><h2>CRM під контролем</h2></div></div><p className="ai-copy">Бачу {clients.length} клієнтів, {upcoming.length} майбутніх зйомок і {openTasks.length} відкритих задач.</p><button className="secondary" onClick={()=>setMurketolog(true)}>Відкрити Муркетолога</button></section></div></>;

  const Clients=()=> <><div className="page-heading"><div><p className="eyebrow">CRM</p><h1>Клієнти</h1><p className="muted">Контакти та історія всіх зйомок.</p></div><button className="primary" onClick={()=>setClientModal(true)}><Plus size={17}/> Новий клієнт</button></div><div className="toolbar"><div className="search"><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Пошук за імʼям, Instagram або телефоном"/></div><span className="soft-pill">{clients.length} клієнтів</span></div><section className="panel table-panel"><div className="table-head"><span>Клієнт</span><span>Джерело</span><span>Записів</span><span>Статус</span><span>Дія</span></div>{loading?<div className="empty-state">Завантажую дані…</div>:filtered.length?filtered.map(c=>{const history=shoots.filter(s=>s.client_id===c.id);return <div className="table-row" key={c.id}><div className="client-cell"><div className="avatar">{c.name[0]}</div><div><strong>{c.name}</strong><span>{c.instagram_handle||c.phone||"—"}</span></div></div><span>{c.source||"—"}</span><button className="soft-pill" onClick={()=>{setSelectedClient(c.id);setSection("shoots")}}>{history.length} записів</button><span>{labels[c.lead_status]||c.lead_status}</span><button className="secondary" onClick={()=>{setSelectedClient(c.id);setShootModal(true)}}><Plus size={14}/> Запис</button></div>}):<div className="empty-state">Поки порожньо. Додай першого клієнта.</div>}</section></>;

  const Shoots=()=>{const visible=selectedClient?shoots.filter(s=>s.client_id===selectedClient):shoots;const selected=clients.find(c=>c.id===selectedClient);return <><div className="page-heading"><div><p className="eyebrow">Історія записів</p><h1>{selected?`Зйомки · ${selected.name}`:"Усі зйомки"}</h1><p className="muted">Кожен запис зберігається окремо в історії клієнта.</p></div><button className="primary" onClick={()=>setShootModal(true)}><Plus size={17}/> Новий запис</button></div>{selected&&<button className="secondary" onClick={()=>setSelectedClient("")}>Показати всі записи</button>}<section className="panel table-panel" style={{marginTop:12}}><div className="table-head"><span>Клієнт</span><span>Тип</span><span>Дата</span><span>Сума</span><span>Статус</span></div>{visible.length?visible.map(s=><div className="table-row" key={s.id}><span>{clientById[s.client_id||""]?.name||"—"}</span><span>{s.shoot_type||"Зйомка"}</span><span>{dt(s.shoot_at)}</span><strong>{money(s.price)}</strong><span>{labels[s.status]||s.status}</span></div>):<div className="empty-state">Записів ще немає.</div>}</section></>};

  const Simple=({title,copy}:{title:string;copy:string})=><><div className="page-heading"><div><p className="eyebrow">Oyaka Workspace</p><h1>{title}</h1><p className="muted">{copy}</p></div></div><section className="panel ai-card"><div className="ai-head"><div className="ai-orb"><Sparkles size={20}/></div><div><p className="eyebrow">Муркетолог 🐾</p><h2>Цей розділ оживляємо наступним</h2></div></div></section></>;

  return <main className="app-shell"><aside className={`sidebar ${mobile?"open":""}`}><div className="brand"><div className="brand-mark"><Camera size={20}/></div><div><strong>Oyaka Workspace</strong><span>photo_oyaka · live CRM</span></div></div><button className="mobile-close" onClick={()=>setMobile(false)}><X size={20}/></button><nav>{nav.map(i=>{const Icon=i.icon;return <button key={i.id} className={section===i.id?"nav-item active":"nav-item"} onClick={()=>{setSection(i.id);setMobile(false)}}><Icon size={18}/><span>{i.label}</span></button>})}</nav><div className="sidebar-bottom"><div className="profile"><div className="profile-avatar">О</div><div><strong>Оля</strong><span>{session.user.email}</span></div><button title="Вийти" onClick={async()=>{await supabase.auth.signOut();setSession(null)}}><LogOut size={16}/></button></div></div></aside>{mobile&&<div className="overlay" onClick={()=>setMobile(false)}/>}<div className="workspace"><header className="topbar"><button className="menu-button" onClick={()=>setMobile(true)}><Menu size={20}/></button><span className="top-title">{current}</span><div className="top-actions"><button className="icon-button"><Search size={18}/></button><button className="icon-button notification"><Bell size={18}/></button><button className="quick-add" onClick={()=>setClientModal(true)}><Plus size={17}/> Клієнт</button></div></header><div className="page-content">{section==="dashboard"&&<Dashboard/>}{section==="clients"&&<Clients/>}{section==="shoots"&&<Shoots/>}{section==="calendar"&&<Simple title="Календар" copy="Далі зробимо повноцінний календар зйомок і дедлайнів."/>}{section==="content"&&<Simple title="Контент + Муркетолог" copy="Підключимо контент-план і роботу з дозволеними фото."/>}{section==="finance"&&<Simple title="Фінанси" copy={`У базі ${payments.length} платіжних операцій.`}/>} {section==="analytics"&&<Simple title="Аналітика" copy="Конверсія, середній чек і джерела заявок рахуватимуться з реальних записів."/>}</div></div>{clientModal&&<AddClient session={session} onClose={()=>setClientModal(false)} onDone={load}/>} {shootModal&&<AddShoot session={session} clients={clients} initialClient={selectedClient} onClose={()=>setShootModal(false)} onDone={load}/>} {murketolog&&<div className="crm-modal-backdrop" onMouseDown={()=>setMurketolog(false)}><div className="crm-modal" onMouseDown={e=>e.stopPropagation()}><div className="crm-modal-head"><div><p className="eyebrow">Муркетолог 🐾</p><h2>Що важливо зараз</h2></div><button className="icon-button" onClick={()=>setMurketolog(false)}><X size={18}/></button></div><p className="muted">Бачу {upcoming.length} майбутніх зйомок, {openTasks.length} відкритих задач і {clients.length} клієнтів. Я нічого не надсилаю клієнтам без підтвердження Олі.</p></div></div>}</main>;
}
