"use client";

import { useEffect, useMemo, useState, type FormEvent } from "react";
import type { Session } from "@supabase/supabase-js";
import { BarChart3, Bell, CalendarDays, Camera, ChevronRight, CircleDollarSign, FolderOpen, LayoutDashboard, LogOut, Menu, Plus, Search, Sparkles, Users, WandSparkles, X } from "lucide-react";
import { supabase } from "./supabase";

type Section = "dashboard"|"clients"|"calendar"|"shoots"|"content"|"finance"|"analytics";
type Client = {id:string;name:string;instagram_handle:string|null;phone:string|null;source:string|null;content_consent:boolean;lead_status:string;created_at:string};
type Shoot = {id:string;client_id:string|null;shoot_type:string|null;status:string;shoot_at:string|null;studio:string|null;location:string|null;price:number;deposit:number;deposit_paid:boolean;photo_due_at:string|null;content_consent:boolean};
type Task = {id:string;title:string;due_at:string|null;status:string;kind:string};
type Payment = {id:string;client_id:string|null;amount:number;type:string;paid_at:string;note:string|null};

const nav=[
{id:"dashboard" as Section,label:"Головна",icon:LayoutDashboard},{id:"clients" as Section,label:"Клієнти",icon:Users},{id:"calendar" as Section,label:"Календар",icon:CalendarDays},{id:"shoots" as Section,label:"Зйомки",icon:Camera},{id:"content" as Section,label:"Контент + Муркетолог",icon:WandSparkles},{id:"finance" as Section,label:"Фінанси",icon:CircleDollarSign},{id:"analytics" as Section,label:"Аналітика",icon:BarChart3}];
const labels:Record<string,string>={new:"Нове звернення",qualified:"Уточнено",date_selection:"Підбір дати",waiting_deposit:"Очікує передоплату",booked:"Заброньовано",shoot_done:"Зйомка проведена",editing:"Фото в роботі",delivered:"Завершено",lost:"Втрачено"};
const money=(v:number)=>`${Number(v||0).toLocaleString("uk-UA")} ₴`;
const dt=(v:string|null)=>v?new Intl.DateTimeFormat("uk-UA",{day:"numeric",month:"short",hour:"2-digit",minute:"2-digit"}).format(new Date(v)):"—";
const statusClass=(s:string)=>s==="booked"||s==="delivered"?"status booked":s==="waiting_deposit"||s==="date_selection"?"status waiting":s==="editing"||s==="shoot_done"?"status work":"status new";

function Auth({onSignedIn}:{onSignedIn:(session:Session)=>void}){
 const[email,setEmail]=useState("");const[password,setPassword]=useState("");const[msg,setMsg]=useState("");const[busy,setBusy]=useState(false);
 async function login(e:FormEvent){e.preventDefault();setBusy(true);setMsg("");const{data,error}=await supabase.auth.signInWithPassword({email,password});setBusy(false);if(error){setMsg("Не вдалося увійти. Перевір email і пароль.");return}if(data.session){onSignedIn(data.session);return}setMsg("Вхід підтверджено, але сесію не отримано. Спробуй ще раз.");}
 async function signup(){if(password.length<6){setMsg("Пароль має містити мінімум 6 символів.");return}setBusy(true);const{data,error}=await supabase.auth.signUp({email,password});setBusy(false);if(error)setMsg(error.message);else if(data.session)onSignedIn(data.session);else setMsg("Акаунт створено. Перевір пошту та підтвердь email.");}
 return <main className="auth-shell"><section className="auth-card"><div className="auth-brand"><div className="brand-mark"><Camera size={21}/></div><div><strong>Oyaka Workspace</strong><span>photo_oyaka · робоче середовище</span></div></div><p className="eyebrow">LIVE CRM</p><h1>Привіт, Олю 👋</h1><p className="muted">Увійди, щоб працювати з реальними клієнтами та зйомками.</p><form className="auth-form" onSubmit={login}><label>Email<input type="email" required value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Пароль<input type="password" required value={password} onChange={e=>setPassword(e.target.value)}/></label>{msg&&<div className="auth-message">{msg}</div>}<button className="primary auth-primary" disabled={busy}>{busy?"Зачекай…":"Увійти"}</button><button className="secondary auth-secondary" type="button" onClick={signup} disabled={busy}>Створити акаунт</button></form></section></main>;
}

function AddClient({session,onClose,onDone}:{session:Session;onClose:()=>void;onDone:()=>void}){
 const[name,setName]=useState("");const[ig,setIg]=useState("");const[phone,setPhone]=useState("");const[source,setSource]=useState("Instagram");const[consent,setConsent]=useState(false);const[busy,setBusy]=useState(false);const[err,setErr]=useState("");
 async function save(e:FormEvent){e.preventDefault();setBusy(true);const{error}=await supabase.from("clients").insert({user_id:session.user.id,name,instagram_handle:ig||null,phone:phone||null,source,content_consent:consent,lead_status:"new"});setBusy(false);if(error){setErr(error.message);return}onDone();onClose();}
 return <div className="crm-modal-backdrop" onMouseDown={onClose}><form className="crm-modal" onSubmit={save} onMouseDown={e=>e.stopPropagation()}><div className="crm-modal-head"><div><p className="eyebrow">Новий контакт</p><h2>Додати клієнта</h2></div><button type="button" className="icon-button" onClick={onClose}><X size={18}/></button></div><div className="form-grid"><label className="full">Імʼя<input required value={name} onChange={e=>setName(e.target.value)} placeholder="Марія Коваль"/></label><label>Instagram<input value={ig} onChange={e=>setIg(e.target.value)} placeholder="@maria"/></label><label>Телефон<input value={phone} onChange={e=>setPhone(e.target.value)} placeholder="+380..."/></label><label>Джерело<select value={source} onChange={e=>setSource(e.target.value)}><option>Instagram</option><option>Рекомендація</option><option>TikTok</option><option>Інше</option></select></label><label className="check-label"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/> Є дозвіл на контент</label></div>{err&&<div className="auth-message">{err}</div>}<div className="modal-actions"><button type="button" className="secondary" onClick={onClose}>Скасувати</button><button className="primary" disabled={busy}>{busy?"Зберігаю…":"Додати"}</button></div></form></div>;
}

function Stat({label,value,sub,Icon}:{label:string;value:string;sub:string;Icon:any}){return <div className="stat-card"><div className="stat-icon"><Icon size={19}/></div><div><p>{label}</p><strong>{value}</strong><span>{sub}</span></div></div>}

export default function CrmApp(){
 const[session,setSession]=useState<Session|null>(null);const[ready,setReady]=useState(false);const[section,setSection]=useState<Section>("dashboard");const[mobile,setMobile]=useState(false);const[clients,setClients]=useState<Client[]>([]);const[shoots,setShoots]=useState<Shoot[]>([]);const[tasks,setTasks]=useState<Task[]>([]);const[payments,setPayments]=useState<Payment[]>([]);const[query,setQuery]=useState("");const[modal,setModal]=useState(false);const[loading,setLoading]=useState(false);
 useEffect(()=>{let active=true;const fallback=window.setTimeout(()=>{if(active)setReady(true)},1800);supabase.auth.getSession().then(({data})=>{if(!active)return;setSession(data.session);setReady(true)}).catch(()=>{if(active)setReady(true)});const{data}=supabase.auth.onAuthStateChange((_e,s)=>{if(!active)return;setSession(s);setReady(true)});return()=>{active=false;window.clearTimeout(fallback);data.subscription.unsubscribe()}},[]);
 async function load(){if(!session)return;setLoading(true);const[c,s,t,p]=await Promise.all([supabase.from("clients").select("*").order("created_at",{ascending:false}),supabase.from("shoots").select("*").order("shoot_at",{ascending:true}),supabase.from("tasks").select("*").order("due_at",{ascending:true}),supabase.from("payments").select("*").order("paid_at",{ascending:false})]);setClients((c.data as Client[])||[]);setShoots((s.data as Shoot[])||[]);setTasks((t.data as Task[])||[]);setPayments((p.data as Payment[])||[]);setLoading(false)}
 useEffect(()=>{if(session)load()},[session]);
 const filtered=useMemo(()=>clients.filter(c=>`${c.name} ${c.instagram_handle||""} ${c.phone||""}`.toLowerCase().includes(query.toLowerCase())),[clients,query]);
 const clientById=useMemo(()=>Object.fromEntries(clients.map(c=>[c.id,c])),[clients]);const open=tasks.filter(t=>t.status==="open");const upcoming=shoots.filter(s=>s.shoot_at&&new Date(s.shoot_at)>=new Date());const booked=shoots.filter(s=>s.status==="booked").length;const income=payments.filter(p=>["deposit","balance"].includes(p.type)).reduce((a,p)=>a+Number(p.amount),0);const current=nav.find(n=>n.id===section)?.label;
 if(!ready)return <main className="auth-shell"><section className="auth-card">Завантажую Oyaka Workspace…</section></main>;if(!session)return <Auth onSignedIn={s=>{setSession(s);setReady(true)}}/>;
 const Dashboard=()=> <><div className="page-heading"><div><p className="eyebrow">Oyaka Workspace · live CRM</p><h1>Доброго дня, Олю 👋</h1><p className="muted">Це вже реальні дані з Supabase, не демо.</p></div><button className="primary" onClick={()=>setModal(true)}><Plus size={17}/> Додати клієнта</button></div><div className="stats-grid"><Stat label="Клієнти" value={String(clients.length)} sub="у базі" Icon={Users}/><Stat label="Бронювання" value={String(booked)} sub={`${upcoming.length} майбутніх`} Icon={CalendarDays}/><Stat label="Отримано оплат" value={money(income)} sub={`${payments.length} операцій`} Icon={CircleDollarSign}/><Stat label="Відкриті задачі" value={String(open.length)} sub="контролює CRM" Icon={Bell}/></div><div className="dashboard-grid"><section className="panel"><div className="panel-title"><div><h2>Найближчі задачі</h2></div></div><div className="agenda">{open.length?open.slice(0,5).map(t=><div className="agenda-item" key={t.id}><div className="agenda-copy"><strong>{t.title}</strong><span>{dt(t.due_at)}</span></div><span className="soft-pill">{t.kind}</span></div>):<div className="empty-state">Задач поки немає. Вони зʼявляться після створення зйомок.</div>}</div></section><section className="panel ai-card"><div className="ai-head"><div className="ai-orb"><Sparkles size={20}/></div><div><p className="eyebrow">Муркетолог 🐾</p><h2>Я вже бачу живу CRM</h2></div></div><p className="ai-copy">Бачу {clients.length} клієнтів, {upcoming.length} майбутніх зйомок і {open.length} відкритих задач. Далі підключимо автоматичні поради на основі цих даних.</p></section></div></>;
 const Clients=()=> <><div className="page-heading"><div><p className="eyebrow">CRM · реальні дані</p><h1>Клієнти</h1><p className="muted">Демо-клієнтів більше немає — тут тільки записи Олі.</p></div><button className="primary" onClick={()=>setModal(true)}><Plus size={17}/> Новий клієнт</button></div><div className="toolbar"><div className="search"><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Пошук за імʼям, Instagram або телефоном"/></div><span className="soft-pill">{clients.length} клієнтів</span></div><section className="panel table-panel"><div className="table-head"><span>Клієнт</span><span>Джерело</span><span>Контент</span><span>Статус</span><span>Створено</span></div>{loading?<div className="empty-state">Завантажую…</div>:filtered.length?filtered.map(c=><div className="table-row" key={c.id}><div className="client-cell"><div className="avatar">{c.name[0]}</div><div><strong>{c.name}</strong><span>{c.instagram_handle||c.phone||"—"}</span></div></div><span>{c.source||"—"}</span><span>{c.content_consent?"✓ дозволено":"—"}</span><span className={statusClass(c.lead_status)}>{labels[c.lead_status]||c.lead_status}</span><span>{new Date(c.created_at).toLocaleDateString("uk-UA")}</span></div>):<div className="empty-state">Поки порожньо. Додай першого клієнта.</div>}</section></>;
 const Shoots=()=> <><div className="page-heading"><div><p className="eyebrow">Проєкти · live</p><h1>Зйомки</h1><p className="muted">Показуємо реальні зйомки з бази.</p></div></div><section className="panel table-panel"><div className="table-head"><span>Клієнт</span><span>Тип</span><span>Дата</span><span>Сума</span><span>Статус</span></div>{shoots.length?shoots.map(s=><div className="table-row" key={s.id}><span>{clientById[s.client_id||""]?.name||"—"}</span><span>{s.shoot_type||"Зйомка"}</span><span>{dt(s.shoot_at)}</span><strong>{money(s.price)}</strong><span>{s.status}</span></div>):<div className="empty-state">Зйомок ще немає.</div>}</section></>;
 const Simple=({title,copy}:{title:string;copy:string})=><><div className="page-heading"><div><p className="eyebrow">LIVE CRM</p><h1>{title}</h1><p className="muted">{copy}</p></div></div><section className="panel ai-card"><div className="ai-head"><div className="ai-orb"><Sparkles size={20}/></div><div><p className="eyebrow">Муркетолог 🐾</p><h2>База вже підключена</h2></div></div><p className="ai-copy">Цей розділ підключимо наступним кроком до реальних даних і дій.</p></section></>;
 return <main className="app-shell"><aside className={`sidebar ${mobile?"open":""}`}><div className="brand"><div className="brand-mark"><Camera size={20}/></div><div><strong>Oyaka Workspace</strong><span>photo_oyaka · live CRM</span></div></div><button className="mobile-close" onClick={()=>setMobile(false)}><X size={20}/></button><nav>{nav.map(i=>{const Icon=i.icon;return <button key={i.id} className={section===i.id?"nav-item active":"nav-item"} onClick={()=>{setSection(i.id);setMobile(false)}}><Icon size={18}/><span>{i.label}</span>{i.id==="content"&&<em>🐾</em>}</button>})}</nav><div className="sidebar-bottom"><div className="storage-card"><FolderOpen size={17}/><div><strong>Сховище фото</strong><span>Google Drive — далі</span></div><ChevronRight size={16}/></div><div className="profile"><div className="profile-avatar">О</div><div><strong>Оля</strong><span>{session.user.email}</span></div><button title="Вийти" onClick={()=>supabase.auth.signOut()}><LogOut size={16}/></button></div></div></aside>{mobile&&<div className="overlay" onClick={()=>setMobile(false)}/>}<div className="workspace"><header className="topbar"><button className="menu-button" onClick={()=>setMobile(true)}><Menu size={20}/></button><span className="top-title">{current}</span><div className="top-actions"><button className="icon-button"><Search size={18}/></button><button className="icon-button notification"><Bell size={18}/><i/></button><button className="quick-add" onClick={()=>setModal(true)}><Plus size={17}/> Клієнт</button></div></header><div className="page-content">{section==="dashboard"&&<Dashboard/>}{section==="clients"&&<Clients/>}{section==="shoots"&&<Shoots/>}{section==="calendar"&&<Simple title="Календар" copy="Підключимо сюди зйомки та дедлайни з бази."/>}{section==="content"&&<Simple title="Контент + Муркетолог" copy="Муркетолог використовуватиме тільки дозволені для контенту зйомки."/>}{section==="finance"&&<Simple title="Фінанси" copy={`У базі вже ${payments.length} платіжних операцій.`}/>} {section==="analytics"&&<Simple title="Аналітика" copy="Конверсія, середній чек і джерела заявок рахуватимуться з реальних записів."/>}</div></div>{modal&&<AddClient session={session} onClose={()=>setModal(false)} onDone={load}/>}</main>;
}
